# Generated by Django 3.2.5 on 2021-07-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='location',
            new_name='estate',
        ),
    ]
