# Generated by Django 3.2.5 on 2021-07-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_alter_neighbourhood_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='Business_name',
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(choices=[('1', 'Retail'), ('2', 'Hospitality'), ('3', 'Hardware'), ('4', 'Health'), ('5', 'Technology')], max_length=200, null=True),
        ),
    ]
