# Generated by Django 3.2.5 on 2021-07-27 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_auto_20210727_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Business_name',
            new_name='business_name',
        ),
    ]
